### ISSUE TITLE
Error: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by jenswilms** [InfuseAI/piperider#182]
**Describe the bug**
'Piperider run' is not fully functioning, it gives the following error: _"Error: unsupported operand type(s) for -: 'NoneType' and 'NoneType'_

The error shows immediately after profiling all the table columns.

**To Reproduce**
1. install piperider with postgres
2. piperider init 
3. piperider run

**Desktop**
 - OS: macOS
 - Python Version [3.9.12]
 - Version [v0.2.0]

**Comment by DaveFlynn** [comment]
Hi @jenswilms 

I was unable to recreate the issue with the same env settings and a test database. If you're using a publicly available dataset could you share it with us?

My advice would be to hang tight for a day or two. PipeRider 0.3.0 will be releasing any day now and comes with lot of fixes and new features.

Dave

**Comment by kentwelcome** [comment]
After investigating, this issue was already fixed in #160.
The next release v0.3.0 will be included this fix.

**Comment by jenswilms** [comment]
Works now! Thanks
