### ISSUE TITLE
Officially supports BigQuery

### ISSUE THREAD

**Issue by yu-iskw** [InfuseAI/piperider#294]
**Is your feature request related to a problem? Please describe.**
We use BigQuery with dbt. It would be awesome for piperider to officially support it.

**Describe the solution you'd like**
I would like piperider to support BigQuery.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by popcornylu** [comment]
Thanks for your feature request. This is our first priority in terms of data source integration. We will reply here if the integration is ready.

**Comment by kentwelcome** [comment]
Currently, dbt BigQuery supports 4 types of auth methods. ref: https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile#authentication-methods

However, sqlAlchemy bigquery hasn't supported access token. We decide not to support dbt method 'oauth-secrets' now. 
There was already a feature PR in sqlAlchemy bigquery project. Once this PR is merged, we can start to support dbt bigquery method `oauth-secrets`
ref: https://github.com/googleapis/python-bigquery-sqlalchemy/pull/459

**Comment by kentwelcome** [comment]
PipeRider will start to support BigQuery from the next release.

**Comment by kentwelcome** [comment]
The PipeRider 0.7.0 had been released!

**Comment by popcornylu** [comment]
Shortcut story
sc-27764
