### ISSUE TITLE
can't use up/down button to select data source in windows terminal

### ISSUE THREAD

**Issue by hlb** [InfuseAI/piperider#298]
**Describe the bug**
can't use up/down button to select data source in windows terminal

**To Reproduce**
1. Execute command: `piperider init`
2. When PipeRider asks data source, user can't use up/down button to select data source.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.4.1

**Comment by kentwelcome** [comment]
After investigating, we found the 3rd library has some related issues on the Windows 
platform. We had fired an issue to the upstream repo. 
In the mine while, we will reimplement the input value handling mechanism on the Windows platform.

**Comment by kentwelcome** [comment]
This issue had been resolved in v0.5.0
