### ISSUE TITLE
Support Snowflake multi-factor authentication

### ISSUE THREAD

**Issue by popcornylu** [InfuseAI/piperider#402]
**Is your feature request related to a problem? Please describe.**
In current snowflake integration, it only supports to login by basic authentication (user/password). If the user enable the [MFA](https://docs.snowflake.com/en/user-guide/security-mfa.html), there is no way to use piperider

**Describe the solution you'd like**
Reference of [snowflake profile in dbt](https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile)

1. run `piperider run`
2. send push notification to Duo Mobile
3. Approve the request
4. Continue

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chenxuanrong** [comment]
Hi @DaveFlynn  @jonycfu,

wonder you have any idea on the above comment ☝️ ?
I'm keen to contribute to this feature and has implemented locally and worked well.

**Comment by DaveFlynn** [comment]
Hi @chenxuanrong 

Thanks for taking the time to contribute!
To submit your contribution please fork the repo, make your changes on a branch and submit a pull request which will be reviewed and merged.

Dave
