### ISSUE TITLE
Fetch table and column description from the data source

### ISSUE THREAD

**Issue by jenswilms** [InfuseAI/piperider#447]
### Problem
The description or table/column could help us to understand the purpose/usage of table or column. Currently, the description can from

1. piperider [config](https://docs.piperider.io/project-structure/config.yml)
2. dbt [model](https://docs.getdbt.com/reference/model-properties) or [source](https://docs.getdbt.com/reference/source-properties) description 

However, it is common that we can get the table or column description from the `information_schema`. For example, in snowflake, we can get the table description from [here](https://docs.snowflake.com/en/sql-reference/info-schema/tables.html#tables-view)

### Expected Outcome
If the table or column has description, show in the report.

### How does it works
- Acquire the description from metadata
- Or from [sqlalchemy metadata](https://docs.sqlalchemy.org/en/13/core/metadata.html#sqlalchemy.schema.Column.params.comment)

**Comment by popcornylu** [comment]
Stale issue
