### ISSUE TITLE
allow Snowflake authentication via externalbrowser

### ISSUE THREAD

**Issue by alexwoolford** [InfuseAI/piperider#532]
It's common for Snowflake users to authenticate using SSO or Snowflake key/pair rather than username/password.

e.g. Jupyter using SSO:

> ```
> conn = connect(
>     user=os.getenv('SNOWFLAKE_USER'),
>     account=os.getenv('SNOWFLAKE_ACCOUNT'),
>     authenticator="externalbrowser",
> )
> 
> cursor = conn.cursor()
> cursor.execute(sql)
> 
> # ... etc...
> ```

Great Expectations `great_expectations.yml` using SSH key/pair:

> ```
> config_version: 3.0
> 
> datasources:
>   my_snowflake:
>     class_name: Datasource
>     module_name: great_expectations.datasource
>     execution_engine:
>       module_name: great_expectations.execution_engine
>       credentials:
>         host: <REDACTED>.us-east-1
>         username: <REDACTED>
>         query:
>           schema: <REDACTED>
>           warehouse: <REDACTED>
>           role: <REDACTED>
>         private_key_path: /path/to/key/rsa_key.p8
>         private_key_passphrase: <REDACTED>
>         drivername: snowflake
>       class_name: SqlAlchemyExecutionEngine
> ```

It would be great if PipeRider did that too, out-of-the-box. 🚗

**Comment by alexwoolford** [comment]
My quick & dirty hacky workaround to use the `externalbrowser` authentication method:

Edit `piperider_cli/datasource/snowflake.py`

Add the authenticator field to the list of fields:

	TextField('authenticator', description='Authenticator'),

Add the authenticator key/value to the `db_parameters` dictionary:

	"authenticator": authenticator,

Add `externalbrowser` to the list of valid autheticators, e.g. this line:

	if authenticator not in ['snowflake', 'username_password_mfa']:

  becomes:

	if authenticator not in ['snowflake', 'username_password_mfa', 'externalbrowser']:

That was way easier than I expected.

**Comment by popcornylu** [comment]
Thanks!! Will try the fix you provide.

**Comment by popcornylu** [comment]
Available in [v0.15.0](https://github.com/InfuseAI/piperider/releases/tag/v0.15.0)
