### ISSUE TITLE
profiler fails when date values span a very large range

### ISSUE THREAD

**Issue by alexwoolford** [InfuseAI/piperider#533]
I have an edge case in my source data where the range of dates in a column spans an absurdly wide range. These are technically valid dates in Snowflake but, in reality, these extreme values are caused by a data integrity issue.

When I try to profile a table with such extreme date values, PipeRider throws an error:
```
[1/1]   my_table_with_a_redacted_name          ━━━━━━━╸━━━━━━━━━━━━━━━   4/9 0:00:06
Error: Profiler Exception: ValueError('year 10001 is out of range')
```

I took a look at the status of the variables in `profiler.py` and notice that:
```
dmin = 0001-01-01
dmax = 9221-01-01
```

Clearly that makes no sense, even if these are technically valid dates.

I was able to get the profiler working, for this table, by increasing the number of buckets. I edited [line 1184 in profiler.py](https://github.com/InfuseAI/piperider/blob/main/piperider_cli/profiler/profiler.py#L1184). From:

`interval_years = math.ceil((dmax.year - dmin.year) / 50)`

to:

`interval_years = math.ceil((dmax.year - dmin.year) / 10000)`

This made the histogram trickier to read (i.e. almost all the values were squished into a handful of buckets), but that's certainly better than an error message and no profiling report:

![histogram-is-a-bit-ugly-better-than-no-report](https://user-images.githubusercontent.com/1839056/206969842-e36b28cc-f27e-407a-8fc4-5c6e2b179d50.png)

From a users perspective, it's not clear from the error message what action can be taken to get a profiling report. My dirty hack (increasing the number of buckets from 50 to 10k) allowed me to get a profile report. That's better than no profile report.

I'm not sure what the right solution is. I do think it shouldn't just fail when date ranges span a very wide range.

**Comment by popcornylu** [comment]
Thanks for your feeback. It's an overflow issue when calculating the bin edge. We will find a way to fix it.
