### ISSUE TITLE
value overflow when profiling table with large numeric IDs

### ISSUE THREAD

**Issue by alexwoolford** [InfuseAI/piperider#541]
I'm new to PipeRider and have really enjoyed it so far. The ease-of-use is pretty remarkable. 

I've profiled a number of databases over the last few days and ran into an issue, in a handful of databases, where numeric ID columns cause an overflow error that prevents the profiler from processing a table. E.g. 

> [ 9/33] <redacted_table_name>                           0/31 0:00:15
> Error: Profiler Exception: ProgrammingError('(snowflake.connector.errors.ProgrammingError) 100058 (22000): Value overflow in a SUM aggregate
> [SQL: WITH anon_2 AS 
> (SELECT <redacted_table_name>.<redacted_numeric_id> AS c, <redacted_table_name>.<redacted_numeric_id>  AS orig
> FROM <redacted_table_name> ), 
> anon_1 AS 
> (SELECT anon_2.c AS c, CASE WHEN (anon_2.c = %(c_1)s) THEN %(param_1)s END AS zero, CASE WHEN (anon_2.c < %(c_2)s) THEN %(param_2)s END AS negative, anon_2.orig AS orig
> FROM anon_2)
>  SELECT count(*) AS _total, count(anon_1.orig) AS _non_nulls, count(anon_1.c) AS _valids, count(anon_1.zero) AS _zeros, count(anon_1.negative) AS _negatives, count(DISTINCT anon_1.c) AS _distinct, sum(CAST(anon_1.c AS FLOAT)) AS _sum, avg(anon_1.c) AS _avg, min(anon_1.c) AS _min, max(anon_1.c) AS _max, stddev(anon_1.c) AS _stddev
> FROM anon_1]
> [parameters: {'c_1': 0, 'param_1': 1, 'c_2': 0, 'param_2': 1}]
> (Background on this error at: https://sqlalche.me/e/14/f405)')

The first time this happened I thought it was an obscure edge-case. I removed the problematic table from `config.yml` and moved on. In my environment, large numeric ID columns are fairly common, and the boxplot of the numeric ID values isn't meaningful. The result of this behavior is that we skip profiling some of our most frequently used data assets.

A quick & dirty workaround would be to copy the entire table, drop the problematic column, document its existence, and profile the copy. That would result in the generated HTML reports becoming disorganized. It's also expensive and slow.

Perhaps `config.yml` could be modified to accept an optional "exclude_column" property for any table in the `includes` list. Or maybe PipeRider could optionally warn on error, instead of fail. Or perhaps there's a way to write the profiling SQL statements to capture the data in a way that doesn't cause the overflow.

If a table has 100 columns, and it was possible to profile 99 without any errors, I'm sure there are other people like me who'd prefer to have 99 profiled columns and a warning rather than an error and no report.

**Comment by david-k-johnson** [comment]
@popcornylu This should be closed with the above merge?

**Comment by clkao** [comment]
Closed by #557
