### ISSUE TITLE
Support multiple db and schema when using dbt state

### ISSUE THREAD

**Issue by david-k-johnson** [InfuseAI/piperider#556]
**Is your feature request related to a problem? Please describe.**
Yes, when using dbt as a datasource it currently does not work at all if your db has custom databases and schemas per group of tables.  I have a WIP fix that I might make a PR for that basically looks at dbt state dir and figures out all databases(using snowflake) and schemas for each grouping of tables then profiles them all, concating all the reports into one.  The WIP is working for me but is a little bit rough at the moment
 
**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
I am not sure a clean one exists if running on a dbt project that has custom database and schema macros

**Additional context**

**Comment by popcornylu** [comment]
We will support custom databases in the coming release v0.18.0 (Hopefully by the end of this week). I will leave comment here if this feature is available.
