### ISSUE TITLE
Validation fails when db only has views but include_views=True

### ISSUE THREAD

**Issue by david-k-johnson** [InfuseAI/piperider#558]
**Describe the bug**
When using the include_views feature, it would be nice if the db only has views that validation/diagnosing would still work.  Currently the code only to see if any tables exist, but if the feature of include_views is turned on it should look for the existence of tables and/or views 

**To Reproduce**
`piperider init`
edit config.yml to make `include_views=true`
run `piperider diagnose` -> Fails
and/or
run `piperider run` -> Fails

**Expected behavior**
Diagnose and/or run(validation) passes if there only views in the db

**Screenshots**
None

**Desktop (please complete the following information):**
Does not matter

**Additional context**

**Comment by david-k-johnson** [comment]
@popcornylu Can we tag and close this issue with PR: https://github.com/InfuseAI/piperider/pull/559

**Comment by clkao** [comment]
closed by #559
