### ISSUE TITLE
Cannot run piperider 

### ISSUE THREAD

**Issue by evelinasamuelsson** [InfuseAI/piperider#571]
**Describe the bug**
Trying to follow the quick start guide to install and begin to use piperider with dbt using vs code. I could do all the steps until run. So init and diagnose worked fine but run gave me an error.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup environment:  
2. Execute command: piperider run
4. See error: _Error: Profiler Exception: TypeError('SQLCompiler.__init__() got multiple values for argument 'cache_key'')_

**Expected behaviour**
I expected it to be able to run

**Screenshots**
![Skärmavbild 2023-01-20 kl  14 25 13](https://user-images.githubusercontent.com/48891813/213714324-b0e6aa07-f9a8-4d7a-8f54-17ae5000e8b5.png)

**Desktop (please complete the following information):**
 - OS: macOS v.12.6
 - Processor: 2,6 GHz 6-Core Intel Core i7
 - dbt version: 1.3.0
 - Python Version: 3.10.8
 - Version: piperider version 0.17.1

**Comment by popcornylu** [comment]
Thanks for your report. May i know the database/datawarehouse you connect to?

**Comment by popcornylu** [comment]
I found the issue by google
https://github.com/googleapis/python-bigquery-sqlalchemy/issues/83

If you installed sqlalchemy 1.4, you have to make sure that pybigquery >= 0.8 
```
$ pip list | grep 'pybigquery\|sqlalchemy'
pybigquery                    0.10.2
SQLAlchemy                    1.4.45
```

**Comment by popcornylu** [comment]
Change to use https://github.com/googleapis/python-bigquery-sqlalchemy since v0.22.0
