### ISSUE TITLE
Does `piperider` support Databricks via the `dbt-databricks` adapter? 

### ISSUE THREAD

**Issue by followingell** [InfuseAI/piperider#619]
As per the title, I'd just like to check whether you currently support Databricks via the [`dbt-databricks`](https://github.com/databricks/dbt-databricks) adapter? _I coudn't find anything in the docs._

**Comment by DaveFlynn** [comment]
Hi @followingell,

We aim to support as many platforms as possible, and databricks is in our sights, but there is currently no date set for adding this connector. 

A few people have requested this recently, and we are discussing it internally.

Thanks for showing an interest in PipeRider.

Dave

**Comment by DaveFlynn** [comment]
Hi @followingell 

We've got some good news for you!

Databricks support was added to PipeRider from version 0.30.0, released yesterday.

You can install with the following command:

`pip install -U 'piperider[databricks]'`

After installing, no further configuration is necessary, you can run the following command on a feature branch to compare your code changes with merge base.

`piperider compare --select state:modified+ `

Alternatively, you can tag the models you want PipeRider to run on. Please refer to the [specifying resources to profile](https://docs.piperider.io/get-started/specify-resources-to-profile) documentation for more information.  

If you have any questions, or issues getting started please let me know.

Dave
