### ISSUE TITLE
can't add metrics to my project 

### ISSUE THREAD

**Issue by isiuni01** [InfuseAI/piperider#681]
Every time i add a Metrics to my bdt project it runs with no error, but when i run piperider there is an error: "Error: list index out of range"

I got the same error on jaffle_shop Project and on my simple project. If i delate the metric the error stop to exist

**To Reproduce**
1. use dbt init(and config your data source) and add a simple model to bdt and a simple metric 
2. run DBT
3. run Piperider

**OS**
 - OS: Windows
 - Python Version 3.10
 - Version : 0.23.3
 - DB: PostgreSQL

**Comment by DaveFlynn** [comment]
Hi @isiuni01 ,

To help debug this issue, would you be able to provide the target/manifest.json from your dbt project?

If the error occurs in your jaffle shop project that might be better to share publicly than your personal project.

If the file is large please email to support@piperider.io

Thanks,

Dave

**Comment by isiuni01** [comment]
hi @DaveFlynn ,

i have send the file at support@piperider.io.

 thank you for your time 

Isiuni

**Comment by isiuni01** [comment]
Thank you! 
Now It works!!
