### ISSUE TITLE
No table to profile

### ISSUE THREAD

**Issue by aahmedomar** [InfuseAI/piperider#686]
**Describe the bug**
I'm seeing a bug where, even though the system is reporting that everything is okay, when I run the `piperider run` tool to profile models I get profile 0 models, it is skipping 85 models with the "notag=85" message. Additionally, there is no table to profile and no metric available for querying.

```commandline
──────────────────────────────────────────────────────────────────── Validating ─────────────────────────────────────────────────────────────────────
everything is OK.
───────────────────────────────────────────────────────────────────── Profiling ─────────────────────────────────────────────────────────────────────
profile 0 models, skip 85 models (notag=85)

No table to profile
────────────────────────────────────────────────────────────────────── Metrics ──────────────────────────────────────────────────────────────────────
no metric for query
────────────────────────────────────────────────────────────────────── Summary ──────────────────────────────────────────────────────────────────────

```

**To Reproduce**
1. Setup environment 'piperider[snowflake]'
2. Execute command 'piperider init'
4. See error = `No table to profile` & `no metric for query`

**Expected behavior**
`To Populate the Table and Show the Report`

**Desktop (please complete the following information):**
 - Windows 11
 - Python Version Python 3.10.11
 - Version 0.24.1

**Additional context**

**Comment by popcornylu** [comment]
Thanks for your question. Starting from [v0.23.0](https://github.com/InfuseAI/piperider/releases/tag/v0.23.0), we have made some default behavioral changes. 

As profiling is a resource-intensive operation, we now require you to add tags to your models before we will perform profiling on them. You can refer to the steps in our [quick start](https://docs.piperider.io/get-started/quick-start#configure-multiple-models-via-dbt-tags) guide for instructions on how to add tags to your models

There are three ways to add tag [dbt tag document](https://docs.getdbt.com/reference/resource-configs/tags). 
- Profile file
- Config property
- Config block

Here is a quick way to add all models to be profiled by the profile file.

```yaml
# dbt_project.yml
models:
  jaffle_shop:
      marts:
        +tags: piperider
```
