### ISSUE TITLE
Show total run time and run time for each data model

### ISSUE THREAD

**Issue by Balurc** [InfuseAI/piperider#704]
It would be nice if you can track the run time for each data model, and put the stats in the report.

It might help the users to answer the following questions:
- What are my slowest-running data models?
- Is my total run time increasing or decreasing with new code changes? With this information, users knows which data models they need to optimize (in case the data pipeline runs very slow and causing a big problem).

**Comment by DaveFlynn** [comment]
Thanks for the suggestion @Balurc 
This feature was added to PipeRider recently, and the dbt execution time is now displayed in the following places:

**The Comparison Report Impact Summary**

![Screenshot 2023-08-11 at 5 09 08 PM](https://github.com/InfuseAI/piperider/assets/128156/43afa875-4bc8-458d-98be-825b66e16f26)


**The Lineage Diff DAG**

![Screenshot 2023-08-11 at 5 09 32 PM](https://github.com/InfuseAI/piperider/assets/128156/26e56746-34d3-4628-a13c-1f221cb85ebb)


**Sample Report**

Here's a sample report to see it in action:

- [PipeRider Data Impact Report showing increased dbt execution time](https://cloud.piperider.io/Dave/default/runs/bb738278520a4ab188f3280049bb1a4a/comparison/3f72f35f34b34125b591e6d7fd1b6a5d)


We'd love your feedback if you get a chance to check it out.

Dave

**Comment by Balurc** [comment]
Thats great @DaveFlynn! Will check it out
