### ISSUE TITLE
Privilege issue on windows, piperider requires to run it under admin

### ISSUE THREAD

**Issue by omazuros** [InfuseAI/piperider#791]
**Describe the bug**
Getting this error while running the comparison report.

Warning: [WinError 1314] A required privilege is not held by the client:
To solve this, run piperider as an administrator  
Error: 'charmap' codec can't encode character '\u2193' in position 1171: character maps to <undefined>

**To Reproduce**
Did 2 runs of dbt and piperiders runs, after that triggered piperider compare last reports.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Python Version 3.9.6
 - Version [e.g. v0.1.3.14]

**Additional context**
DBT version 1.3

**Comment by DaveFlynn** [comment]
Thanks for reporting this bug @omazuros 
The team is investigating and I'll post an update as soon as I know more.

Dave

**Comment by DaveFlynn** [comment]
Hi @omazuros 

We fixed some bugs related to Windows which should have resolved this issue in PipeRider 0.30.0+

Please update to the latest version of PipeRider and try again:

```
pip install -U piperider
```

Let us know if it works for you!

Thanks,

Dave
