### ISSUE TITLE
Error installing piperider for Snowflake

### ISSUE THREAD

**Issue by marcellovictorino** [InfuseAI/piperider#833]
**Describe the bug**
After installing `piperider[snowflake]`, not able to run `piperider diagnose`, raising error:
```
PipeRiderConnectorError: cannot import name 'PY2' from 'snowflake.connector.compat' 
```

**To Reproduce**
1. Setup environment 'pyenv install 3.9.17 && python -m venv .venv && source .venv/bin/activate && pip install `piperider[snowflake]''
2. Execute command 'piperider diagnose'
4. See error: `PipeRiderConnectorError: cannot import name 'PY2' from 'snowflake.connector.compat' `

**Expected behavior**
The diagnose should identify the valid `profiles.yml` and verify connection with snowflake.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS M2 Pro | Venture 13.4.1
 - Python Version 3.9.17
 - Version (piperider): 0.30

**Additional context**
full output of `piperider diagnose --debug`:
```
piperider diagnose --debug
Diagnosing...
PipeRider Version: 0.30.0
Check config files:
  /.../.piperider/config.yml: [OK]
✅ PASS

Check format of data sources:
  dev: [OK]
  prod: [OK]
✅ PASS

Check connections:
  DBT: snowflake > analytics > dev [OK]
  Name: dev
  Type: snowflake
  connector: [FAILED] reason: cannot import name 'PY2' from 'snowflake.connector.compat' 
(/.../.venv/lib/python3.9/site-packages/snowflake/connector/compat.py)

Please run "pip install 'piperider[snowflake]'" to get the snowflake connector

😱 FAILED

Error: CheckConnections: cannot import name 'PY2' from 'snowflake.connector.compat' 
(/.../.venv/lib/python3.9/site-packages/snowflake/connector/compat.py)
Hint:
  Please run "pip install 'piperider[snowflake]'" to get the snowflake connector
```

**Comment by DaveFlynn** [comment]
Hi @marcellovictorino,

Thanks for submitting this issue.
Our team is currently looking into this and I'll let you know as soon as we know more.

Dave

**Comment by clkao** [comment]
@marcellovictorino this looks like a dependency compatibility issue. can you check versions of the related packages with:

    % pip list | grep snowflake

And try upgrading them to see if they work.

we'll see how we can avoid dependency combinations that break.

**Comment by whanata** [comment]
I have the same issue and I ran `poetry show | grep "snowflake"`.

This is the output:
```
dbt-snowflake              1.4.1     The Snowflake adapter plugin for dbt
snowflake-connector-python 2.7.12    Snowflake Connector for Python
```

**Comment by DaveFlynn** [comment]
Hi @marcellovictorino @whanata 

Our team was able to reproduce the issue with your specific package versions, and discovered that this may be related to the latest version of `sqlalchemy-snowflake`  using a module which is only available in the latest `python-connector`.

Could you please try with these versions:

```
snowflake-connector-python 3.1.0
snowflake-sqlalchemy       1.4.7
```

Please let us know how you get on.

Dave

**Comment by popcornylu** [comment]
The way to reproduce it is to run the following commands

```
$ python -m venv ./venv
$ source ./venv/bin/activate
$ pip install snowflake-connector-python==2.7.12
$ pip install snowflake-sqlalchemy==1.0.8
$ python -c 'import snowflake.sqlalchemy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/__init__.py", line 8, in <module>
    from .util import _url as URL
  File "/private/tmp/snowflake/venv/lib/python3.10/site-packages/snowflake/sqlalchemy/util.py", line 9, in <module>
    from ..connector.compat import (PY2, IS_STR)
ImportError: cannot import name 'PY2' from 'snowflake.connector.compat' (/private/tmp/snowflake/venv/lib/python3.10/site-packages/snowflake/connector/compat.py)
```

To solve this, upgrade the `snowflake-sqlalchemy` to >= `1.4.3`
```
$  pip install snowflake-sqlalchemy==1.4.3        
$ python -c 'import snowflake.sqlalchemy' 
```

**Comment by marcellovictorino** [comment]
Hello, all!
Thanks for the super support here! Indeed, I managed to solve the issue by force updating the transient dependency `snowflake-sqlalchemy`

In my case, I am using Poetry as the dependency manager, so the `pyproject.toml` file looks like this:
```toml
dbt-snowflake = "~1.3.0"
piperider = { extras = ["snowflake"], version = "^0.30.0" }
snowflake-sqlalchemy = "~1.4.3"
```

**Comment by marcellovictorino** [comment]
By the way, previously when installing `piperider[snowflake]`, it kept using an older version of `snowflake-sqlalchemy` (1.0.8), which caused the problem.

Force updating to >=1.4 brought all the other versions to latest, and they were all happy ever after 🤣

**Comment by whanata** [comment]
Sorry for the late reply, I got it working now, thanks for the support :)
