### ISSUE TITLE
Support for `dbt-core~1.7.0`

### ISSUE THREAD

**Issue by waligob** [InfuseAI/piperider#928]
**Is your feature request related to a problem? Please describe.**
We would like to update to [the 1.7 release of dbt-core](https://github.com/dbt-labs/dbt-core/releases/tag/v1.7.0). Piperider is [currently constrained](https://github.com/InfuseAI/piperider/blob/ad3ce422134df75455a55f6d3d6cdb92b653e814/setup.py#L48) to `dbt-core>=1.3,<1.7`

**Describe the solution you'd like**
Ability to install Piperider alongside `dbt-core~1.7.0`

**Describe alternatives you've considered**
_N/A_

**Additional context**
_N/A_

**Comment by popcornylu** [comment]
Hi @waligob, Thank you for your feedback. Definitely, we will support dbt 1.7.

For internal tracking sc-32598

**Comment by DaveFlynn** [comment]
Thanks @waligob. 
This is scheduled for the next PipeRider release on 10/23. We'll update you once it is released.

**Comment by waligob** [comment]
Thanks for the responses, all. @DaveFlynn, do you mean 11/23?

**Comment by DaveFlynn** [comment]
@waligob  yes, that's correct! Thanks

**Comment by popcornylu** [comment]
Available in 0.41.0
